# Generated by Django 4.2.16 on 2024-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=125, verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price')),
                ('published', models.DateField(blank=True, default=None, null=True, verbose_name='Publish Date')),
                ('is_published', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Image')),
            ],
        ),
    ]
